service: werewolves

frameworkVersion: "3"

plugins:
    - serverless-python-requirements
    - serverless-offline

provider:
    name: aws
    runtime: python3.9

functions:
    hello:
        handler: handler.hello
