service: werewolves

frameworkVersion: "3"

plugins:
    - serverless-python-requirements
    - serverless-offline

provider:
    name: aws
    runtime: python3.9

functions:
    hello1:
        handler: handler.hello
        events:
            - httpApi: "GET /hello1"
