service: werewolves

frameworkVersion: "3"

plugins:
    - serverless-python-requirements
    - serverless-offline

provider:
    name: aws
    runtime: python3.9

functions:
    startGame:
        handler: handler.start
        events:
            - httpApi: "GET /start"
    endGame:
        handler: handler.end
        events:
            - httpApi: "GET /end"
